---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: yaspokoyen/java-maven-example:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: app
spec:
  ports:
  - port: 80
    targetPort: 8081
    name: tcp
  selector:
    app: java-app